---
--- Generated by Luanalysis
--- Created by 23849.
--- DateTime: 2024/8/6 15:47
---
-- 比较线程标示是否一致
if(redis.call('get',KEYS[1] == ARGV[1])) then
    -- 释放锁 del key
    return redis.call('del',KEYS[1])
end
return 0